# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Code_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_and_crossword.Code')),
            ],
        ),
        migrations.CreateModel(
            name='Crossword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=3000)),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Crossword_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=3000)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='code_and_crossword.Code')),
            ],
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sub_date', models.DateTimeField(verbose_name='submission date')),
                ('score', models.IntegerField()),
                ('code_score', models.IntegerField()),
                ('crossword_score', models.IntegerField()),
            ],
        ),
    ]
