# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_and_crossword', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='code_answer',
            name='question',
        ),
        migrations.RemoveField(
            model_name='crossword_answer',
            name='question',
        ),
        migrations.DeleteModel(
            name='Code_Answer',
        ),
        migrations.DeleteModel(
            name='Crossword_Answer',
        ),
    ]
